name: JVM Tests

on:
  push:
  pull_request:

jobs:
  vm-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test:
          - name: ReturnTest
            expected: 69
          - name: OptimizedAddTest
            expected: 75
          - name: AddTest
            expected: 8

    name: Test ${{ matrix.test.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Compile Java test
        run: |
          javac \
            -source 8 \
            -target 8 \
            tests/${{ matrix.test.name }}.java

      - name: Build dioptase
        run: cargo build --release

      - name: Run test
        run: |
          set +e

          ./target/release/dioptase tests/${{ matrix.test.name }}.class
          code=$?

          set -e

          echo "JVM returned: $code"

          test $code -eq ${{ matrix.test.expected }}
